source 'https://rubygems.org'

gem 'sinatra', '~> 2.0', require: 'sinatra/base'
gem 'rake', '~> 12.3'
gem 'thin', '~> 1.7'
gem 'bundler', '>= 1.16', '< 2'

# Database adapters
gem 'sqlite3', '~> 1.3', group: [:development, :test]
gem 'pg', '~> 1.0', group: :production

# ActiveRecord for models and records
gem 'activerecord', '~> 5.2', require: ['active_support','active_support/core_ext']
gem 'sinatra-activerecord', '~> 2.0', require: ['sinatra/activerecord','sinatra/activerecord/rake']

# Test environment
group :test, :production do
    gem 'rack-test', '~> 1.0', require: 'rack/test'
    gem 'rspec', '>= 3.7', '< 4'
    gem 'shoulda-matchers', '~> 3.1'
end

# Logging library
gem 'lumberjack', '~> 1.0'

# Asset pipeline and preprocessors/compressors
gem 'sprockets', '>= 3.7', '< 4'
gem 'sass', '>= 3.5', '< 4'
gem 'uglifier', '>= 4.1', '< 5'

# Markdown and YAML front-matter parsing
gem 'front_matter_parser', '0.2.0'
gem 'rdiscount', '~> 2.2'

# Hanami HTML/asset helpers
group :hanami do
    gem 'hanami-helpers', '~> 1.2', require: 'hanami/helpers'
    gem 'hanami-assets', '~> 1.2', require: ['hanami/assets','hanami/assets/helpers']
end